apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: fishyfish-fish
  name: fishyfish-fish
  namespace: ingress-controller
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: fishyfish-fish
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: fishyfish-fish
    spec:
      containers:
      - image: registry.tr0:5000/fishyfishfish:0.1
        imagePullPolicy: IfNotPresent
        name: fishyfish-fish
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
