apiVersion: v1
kind: Service
metadata:
  name: fishyfish-fish
  namespace: ingress-controller
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: fishyfish-fish
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
